# Default values for br-oauth-proxy-docker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 'brdevregistry.azurecr.io/br-oauth-proxy-docker'
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  # placeholder values should allow the service to install and minimally respond
  container:
    port: 4180
  environment:
    OAUTH2_PROXY_AZURE_TENANT: 'common'
    OAUTH2_PROXY_CLIENT_ID: 'fixme-oauth-sp-client-id'
    OAUTH2_PROXY_COOKIE_EXPIRE: '4320h'
    OAUTH2_PROXY_COOKIE_NAME: 'Bedrock_AUTHN_cf_Dev__utm'
    OAUTH2_PROXY_COOKIE_PATH: '/'
    OAUTH2_PROXY_COOKIE_REFRESH: '1h'
    OAUTH2_PROXY_EMAIL_DOMAINS: '*'
    OAUTH2_PROXY_EXTRA_JWT_ISSUERS: 'fixme-oauth-jwt-id-providers'
    OAUTH2_PROXY_HTTP_ADDRESS: '0.0.0.0:4180'
    OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
    OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: 'true'
    OAUTH2_PROXY_PING_PATH: '/'
    OAUTH2_PROXY_PROVIDER: 'azure'
    OAUTH2_PROXY_REDIRECT_URL: 'fixme-oauth-redirect-url'
    OAUTH2_PROXY_RESOURCE: 'fixme-oauth-proxy-resource'
    OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: 'true'
    OAUTH2_PROXY_SILENCE_PING_LOGGING: 'true'
    OAUTH2_PROXY_SKIP_AUTH_REGEX: 'fixme-oauth-skip-auth-regex'
    OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: 'true'
    OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
    OAUTH2_PROXY_UPSTREAMS: 'fixme-oauth-proxy-upstreams'
    APP_VERSION: '{{ .Chart.AppVersion }}'
  secrets:
    OAUTH2_PROXY_CLIENT_SECRET: 'fixme-oauth-proxy-client-secret'
    OAUTH2_PROXY_COOKIE_SECRET: 'fixme-oauth-proxy-cookie-secret'

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
